table 'Outage Classifications'
	lineageTag: 0de8114b-0a9c-4afa-a511-d5b9bcd2e95f

	column Category
		dataType: string
		lineageTag: fecacacc-c4eb-454a-b4fa-077a27e0938b
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Trigger
		dataType: string
		lineageTag: 7a1985a1-3eed-4cbf-8a5f-889e032c2941
		summarizeBy: none
		sourceColumn: Trigger

		annotation SummarizationSetBy = Automatic

	column Definition
		dataType: string
		lineageTag: 9261ab3e-f670-4c26-a80d-918ce3895b23
		summarizeBy: none
		sourceColumn: Definition

		annotation SummarizationSetBy = Automatic

	partition 'Outage Classifications' = m
		mode: import
		source =
				let
				    Source = Pdf.Tables(File.Contents("C:\Users\Atikant(AJ)\Downloads\Outage-Classifications.pdf"), [Implementation="1.3"]),
				    Table001 = Source{[Id="Table001"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table001,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Category", type text}, {"Trigger", type text}, {"Definition", type text}}),
				    #"Appended Query" = Table.Combine({#"Changed Type1", #"Table002 (Page 3)", #"Table003 (Page 4)"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Appended Query","",null,Replacer.ReplaceValue,{"Category"}),
				    #"Filled Down" = Table.FillDown(#"Replaced Value",{"Category"})
				in
				    #"Filled Down"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

